import 'dart:convert';
import 'dart:io';

import 'package:generator/src/utils.dart';
import 'package:recase/recase.dart';
import 'package:xml/xml.dart';

/// Generator for icon files
class IconFileGenerator {
  static const _symbolMap = {
    '*': 'multiply',
    '-': 'minus',
    '+': 'plus',
    '/': 'divide',
    '=': 'equals',
    '%': 'percent',
    '&': 'and',
    '@': 'at',
  };

  final _buffer = StringBuffer();

  final List<String> _iconNames = [];

  /// Add class definition to generated content
  void addClassDefinition({
    required String iconClassName,
    required String url,
  }) {
    _buffer.writeln('''
/// [$iconClassName] offers the [IconData] of [$url]
@staticIconProvider
abstract final class $iconClassName {
''');
  }

  /// Add font config
  ///
  /// Uses input to generate the icon class members.
  ///
  /// - [file]: XML font file (must be ttx)
  /// - [fontFamily]: Font family name
  /// - [fontPackage]: Font package name
  /// - [iconSvgPath]: Used to create icons in doc strings
  /// - [brand]: Brand name of the icon package
  /// - [suffix]: optional suffix for generated class members
  void addFontConfigFile(
    File file, {
    required String fontFamily,
    required String fontPackage,
    required String iconSvgPath,
    required String brand,

    String suffix = '',
  }) {
    final mimeType = file.path.split('.').last;

    if (mimeType != 'ttx') {
      throw FormatException(
        'Invalid file type. Expected "ttx" but got "$mimeType"',
      );
    }

    final iconsData = _readIcons(file);

    _createIconDataString(
      iconsData,
      fontFamily,
      fontPackage,
      iconSvgPath,
      suffix,
      brand,
    );
  }

  /// Add generic imports
  ///
  /// This adds a generic import header to the generated file.
  void addImports() {
    _buffer.writeln('''
import 'package:flutter/widgets.dart';

// THIS FILE IS AUTOMATICALLY GENERATED!
''');
  }

  /// Add icon value list
  ///
  /// Add a list containing all IconData included in [files].
  void addValues(List<File> files) {
    _buffer.writeln('''
/// A list containing all [IconData] of the icon set.
///
/// **CAUTION**: Accessing this list will effectively disable tree-shaking
/// the icon font. This results in all icons being included in the
/// application, significantly increasing the final bundle size.
static const List<IconData> values = [${_iconNames.join(', ')}];
''');
  }

  /// Build file
  ///
  /// call [writeToFile] to wirte generated content to file.
  void build() {
    _buffer.writeln('}');
  }

  /// Write file
  ///
  /// writes generated content to [file].
  void writeToFile(File file) {
    file.writeAsStringSync(_buffer.toString());
  }

  String _createEncodedIcon(String path) {
    final file = File(path);

    if (!file.existsSync()) {
      return '';
    }

    final document = XmlDocument.parse(file.readAsStringSync());

    document.rootElement
      ..setAttribute('height', '24')
      ..setAttribute('width', '24')
      ..setAttribute('xmlns', 'http://www.w3.org/2000/svg');

    const color = 'gray';

    var foundElement = false;

    for (final node in document.findAllElements('*')) {
      if (node.getAttribute('stroke') == 'currentColor') {
        node.setAttribute('stroke', color);
        foundElement = true;
      }

      if (node.getAttribute('fill') == 'currentColor') {
        node.setAttribute('fill', color);
        foundElement = true;
      }
    }

    // fallback (just fill the icon)
    if (!foundElement) document.rootElement.setAttribute('fill', color);

    final base64Encoded = base64Encode(utf8.encode(document.toXmlString()));

    return '![Icon](data:image/svg+xml;base64,$base64Encoded)';
  }

  void _createIconDataString(
    Map<String, String> iconsData,
    String fontFamily,
    String fontPackage,
    String iconSvgPath,
    String suffix,
    String brand,
  ) {
    iconsData.forEach((iconName, iconUnicode) {
      final parsedNamed = _parseName(iconName);
      final name = suffix.isEmpty ? parsedNamed : '${parsedNamed}_$suffix';

      _iconNames.add(name);

      final iconEncoded = _createEncodedIcon('$iconSvgPath/$iconName.svg');

      if (iconEncoded.isEmpty) {
        stderr.writeln('$iconName.svg not found');
        return;
      }

      _buffer.writeln('''
/// $iconEncoded
///
/// $brand icon named "$iconName".
static const IconData $name = IconData($iconUnicode, fontFamily: '$fontFamily', fontPackage: '$fontPackage');
''');
    });
  }

  String _parseName(String iconName) {
    final iconNameValidated = _validateVariableName(iconName);
    return ReCase(iconNameValidated).camelCase;
  }

  /// read the icon data from the [file]
  Map<String, String> _readIcons(File file) {
    final content = file.readAsStringSync();
    final document = XmlDocument.parse(content);

    final icons = _xmlToIcons(document);
    return icons;
  }

  String _validateVariableName(String name) {
    var sanName = name;

    // name is a symbol
    if (_symbolMap.containsKey(name)) {
      sanName = '${_symbolMap[name]!}_symbol';
    }

    // adds 'icon' suffix to dart keywords
    if (dartKeywords.contains(sanName)) {
      sanName = '${sanName}_icon';
    }

    // adds 'n' before variables that start with a number
    if (sanName.startsWith(RegExp(r'\d'))) {
      sanName = 'n$sanName';
    }
    return sanName;
  }

  Map<String, String> _xmlToIcons(XmlDocument document) {
    final ttFont = document.getElement('ttFont');
    final cmap = ttFont?.getElement('cmap');

    if (cmap == null) {
      throw const FormatException('Could not parse XML');
    }

    final icons = <String, String>{};

    final tables = cmap.children.whereType<XmlElement>().where((node) {
      final pId = node.getAttribute('platformID');
      final eId = node.getAttribute('platEncID');
      final lng = node.getAttribute('language');

      return switch ((pId, eId, lng)) {
        ('0', '3', '0') => true, // Unicode BMP
        ('0', '4', '0') => true, // Unicode Full
        ('3', '1', '0') => true, // Windows Unicode
        _ => false,
      };
    });

    if (tables.isEmpty) {
      throw const FormatException('No valid cmap tables found.');
    }

    for (final table in tables) {
      final maps = table.findElements('map');

      for (final node in maps) {
        final name = node.getAttribute('name');
        final code = node.getAttribute('code');

        if (name != null && code != null) {
          icons[name] = code;
        }
      }
    }

    return icons;
  }
}
