# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 1
  - package-ecosystem: "npm"
    directories:
      - "/vendors/**/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 1
    groups:
      ant-design-icons:
        patterns:
          - "@ant-design*"
      bootstrap-icons:
        patterns:
          - "bootstrap*"
      hero-icons:
        patterns:
          - "hero*"
      ionic-icons:
        patterns:
          - "ionic*"
      lucide-icons:
        patterns:
          - "lucide*"
      primer-icons:
        patterns:
          - "@primer*"
      radix-icons:
        patterns:
          - "@radix*"
      remix-icons:
        patterns:
          - "remix*"
      simple-icons:
        patterns:
          - "simple*"
      tabler-icons:
        patterns:
          - "@tabler*"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 1
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 1
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 1
