import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:generator/generator.dart';

void main() {
  late IconFileGenerator generator;

  setUpAll(() {
    generator = IconFileGenerator();
  });

  group('addClassDefinition', () {
    late File file;

    setUp(() {
      file = File('test.dart');
    });

    tearDown(() {
      if (file.existsSync()) file.deleteSync();
    });

    test('adds the correct class definition and doc', () {
      generator
        ..addClassDefinition(
          iconClassName: 'TestIconClass',
          url: 'https://example.com/icons',
        )
        ..writeToFile(file);

      final content = file.readAsStringSync();

      expect(content, contains('@staticIconProvider'));
      expect(content, contains('abstract final class TestIconClass {'));
      expect(
        content,
        contains(
          '/// [TestIconClass] offers the [IconData] of [https://example.com/icons]',
        ),
      );
    });
  });

  group('addFontConfigFile', () {
    late File file;

    setUp(() {
      file = File('file.ttx');
    });

    tearDown(() {
      if (file.existsSync()) file.deleteSync();
    });

    test('throws FormatException on invalid file type', () {
      final invalidFile = File('invalid_file.txt');

      expect(
        () => generator.addFontConfigFile(
          invalidFile,
          fontFamily: 'TestFont',
          fontPackage: 'test_package',
          iconSvgPath: 'path/to/icons',
          brand: 'TestBrand',
        ),
        throwsA(isA<FormatException>()),
      );
    });

    test('throws FormatException when cmap is missing', () {
      file.writeAsStringSync('<ttFont></ttFont>');

      expect(
        () => generator.addFontConfigFile(
          file,
          fontFamily: 'TestFont',
          fontPackage: 'test_package',
          iconSvgPath: 'path/to/icons',
          brand: 'TestBrand',
        ),
        throwsA(isA<FormatException>()),
      );
    });

    test('throws FormatException when no valid cmap is found', () {
      file.writeAsStringSync('<ttFont><cmap></cmap></ttFont>');

      expect(
        () => generator.addFontConfigFile(
          file,
          fontFamily: 'TestFont',
          fontPackage: 'test_package',
          iconSvgPath: 'path/to/icons',
          brand: 'TestBrand',
        ),
        throwsA(isA<FormatException>()),
      );
    });
  });

  group('addImports', () {
    late File file;

    setUp(() {
      file = File('test.dart');
    });

    tearDown(() {
      if (file.existsSync()) file.deleteSync();
    });

    test('adds the correct import statements and header comment', () {
      generator
        ..addImports()
        ..writeToFile(file);

      final content = file.readAsStringSync();

      expect(content, contains("import 'package:flutter/widgets.dart';"));
      expect(content, contains('// THIS FILE IS AUTOMATICALLY GENERATED!'));
    });
  });

  group('addValues', () {
    late File file;

    setUp(() {
      file = File('test.dart');
    });

    tearDown(() {
      if (file.existsSync()) file.deleteSync();
    });

    test('adds the values list', () {
      generator
        ..addValues()
        ..writeToFile(file);

      final content = file.readAsStringSync();

      expect(content, contains('static const List<IconData> values = ['));
    });
  });

  group('build', () {
    late File file;

    setUp(() {
      file = File('test.dart');
    });

    tearDown(() {
      if (file.existsSync()) file.deleteSync();
    });

    test('adds the closing brace for the class', () {
      generator
        ..build()
        ..writeToFile(file);

      final content = file.readAsStringSync();

      expect(content, contains('}'));
    });
  });

  group('encodeSVG', () {
    test('encodes SVG content correctly', () {
      final encoded = generator.encodeSVG('<svg></svg>');

      expect(encoded, contains('![Icon](data:image/svg+xml;base64,'));

      final base64Content = encoded.split(',')[1].split(')')[0];
      final decoded = utf8.decode(base64.decode(base64Content));

      expect(decoded, contains('<svg'));
      expect(decoded, contains('</svg>'));
      expect(decoded, contains('height="24"'));
      expect(decoded, contains('width="24"'));
      expect(decoded, contains('fill="gray"'));
      expect(decoded, contains('xmlns="http://www.w3.org/2000/svg"'));
    });
  });

  group('parseName', () {
    test('converts snake_case, kebab-case, and spaces to camelCase', () {
      expect(generator.parseName('arrow_up'), 'arrowUp');
      expect(generator.parseName('arrow-down'), 'arrowDown');
      expect(generator.parseName('arrow up'), 'arrowUp');
    });

    test('resolves known symbol names', () {
      expect(generator.parseName('*'), 'multiplySymbol');
      expect(generator.parseName('+'), 'plusSymbol');
      expect(generator.parseName('@'), 'atSymbol');
    });

    test('appends Icon suffix to Dart keywords', () {
      expect(generator.parseName('class'), 'classIcon');
      expect(generator.parseName('switch'), 'switchIcon');
      expect(generator.parseName('void'), 'voidIcon');
    });

    test('prepends n to variables starting with a digit', () {
      expect(generator.parseName('500px'), 'n500px');
      expect(generator.parseName('1-password'), 'n1Password');
    });
  });
}
