name: generator
description: "Icon generator"
publish_to: none

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  recase: ^4.1.0
  xml: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
