name: Auto-update PR branch

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v3
        id: generate-token
        with:
          client-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Automatically update PR
        uses: adRise/update-pr-branch@v0.10
        with:
          token: ${{ steps.generate-token.outputs.token }}
          base: "main"
          required_approval_count: 0
          require_passed_checks: true
          allow_ongoing_checks: true
          sort: "created"
          direction: "desc"
          require_auto_merge_enabled: true
