name: Generate Icons

on:
  pull_request:
    paths:
      - "vendors/**"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      icon_sets: >-
        ${{
          github.event_name == 'workflow_dispatch'
          && '["antdesign", "bootstrap", "hero", "lucide", "remix", "simple", "tabler"]'
          || steps.filter.outputs.changes
        }}
      includes: ${{ steps.set-matrix.outputs.includes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Create include matrix
        id: set-matrix
        run: |
          JSON=$(cat .github/matrix/icon_set_matrix.json | jq -c '.')
          echo "includes=$JSON" >> $GITHUB_OUTPUT

      - name: Filter paths
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            antdesign: vendors/ant_design_icons/**
            bootstrap: vendors/bootstrap_icons/**
            hero: vendors/hero_icons/**
            lucide: vendors/lucide_icons/**
            remix: vendors/remix_icons/**
            simple: vendors/simple_icons/**
            tabler: vendors/tabler_icons/**

  generate:
    needs: changes
    if: ${{ needs.changes.outputs.icon_sets != '[]' && needs.changes.outputs.icon_sets != '' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    name: "${{ matrix.icon_set_name }}"
    strategy:
      fail-fast: false
      matrix:
        icon_set_name: ${{ fromJSON(needs.changes.outputs.icon_sets) }}
        include: ${{ fromJSON(needs.changes.outputs.includes) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install npm dependencies
        working-directory: ./vendors/${{ matrix.config.package_name }}
        run: npm ci

      - name: Get vendor package version
        id: get-version
        working-directory: ./vendors/${{ matrix.config.package_name }}
        run: |
          VERSION=$(npm list ${{ matrix.config.vendor_dir }} --depth=0 --json | jq -er '.dependencies."${{ matrix.config.vendor_dir }}".version')
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Install pip dependencies
        run: pip install -r requirements.txt

      - name: Flatten SVG directories
        if: matrix.config.flatten_svg_dirs == true
        working-directory: ./vendors/${{ matrix.config.package_name }}
        run: |
          for svg_dir in ${{ matrix.config.fonts[*].svg_dir }}; do
            SVG_DIR=$(find . -type d -path "*${{ matrix.config.vendor_dir }}/${svg_dir}")
            find "$SVG_DIR" -mindepth 2 -type f -name "*.svg" -exec mv -t "$SVG_DIR" {} +
          done

      - name: Install svgtofont, SVG Fixer
        if: matrix.config.svg_to_font == true
        run: npm ci

      - name: Convert SVG to Font
        if: matrix.config.svg_to_font == true
        working-directory: ./vendors/${{ matrix.config.package_name }}
        env:
          FONTS_JSON: ${{ toJSON(matrix.config.fonts) }}
        run: |
          echo "$FONTS_JSON" | jq -c '.[]' | while read -r font_item; do
            SVG_DIR=$(echo "$font_item" | jq -r '.svg_dir')
            FONT_FILE=$(echo "$font_item" | jq -r '.file')
            SVG_DIR=$(find . -type d -path "*${{ matrix.config.vendor_dir }}/${SVG_DIR}")
            
            SVG_FIXED_PATH=$(mktemp -d)
            echo "The temporary directory is: $SVG_FIXED_PATH"
            
            npx oslllo-svg-fixer --source "$SVG_DIR" --destination "$SVG_FIXED_PATH" --show-progress true
            npx svgtofont --sources "$SVG_FIXED_PATH" --output "node_modules/${{ matrix.config.vendor_dir }}/fonts" --fontName "${FONT_FILE}"
          done

      - name: Convert WOFF to TTF
        if: matrix.config.convert_from_woff == true
        working-directory: ./vendors/${{ matrix.config.package_name }}
        run: |
          WOFF=$(find . -name "*.woff")
          for woff in $WOFF; do
            ttx ${woff}
            ttx ${woff%.woff}.ttx
          done

      - name: Set Paths
        id: set-paths
        run: |
          FONT_PATH=$(find "vendors/${{ matrix.config.package_name }}/node_modules" -name "*.ttf" -exec dirname {} \; | head -n 1)
          SVG_PATH_BASE=$(find "vendors/${{ matrix.config.package_name }}/node_modules" -type d -path "*${{ matrix.config.vendor_dir }}" | head -n 1)
          echo "font_path=$FONT_PATH" >> "$GITHUB_OUTPUT"
          echo "svg_path_base=$SVG_PATH_BASE" >> "$GITHUB_OUTPUT"

      - name: Generate ttx for ${{ matrix.icon_set_name }}
        run: |
          for font in ${{ join(matrix.config.fonts.*.file, ' ') }}; do
            ttx -t cmap "${{ steps.set-paths.outputs.font_path }}/${font}"
          done

      - name: Copy fonts to package
        run: |
          for font in ${{ join(matrix.config.fonts.*.file, ' ') }}; do
            cp "${{ steps.set-paths.outputs.font_path }}/${font}" "./packages/${{ matrix.config.package_name }}/fonts/${font}"
          done

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Generate icons for ${{ matrix.icon_set_name }}
        run: dart run tools/generate_icons.dart --iconset ${{ matrix.icon_set_name }}

      - name: Format code
        run: dart format ./packages/${{ matrix.config.package_name }}/

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v2
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ steps.generate-token.outputs.token }}
          add-paths: packages/${{ matrix.config.package_name }}/*
          sign-commits: true
          title: "feat(${{ matrix.config.package_name }}): bump version to ${{ steps.get-version.outputs.version }}"
          branch: "feat/update-${{ matrix.config.package_name }}-${{ steps.get-version.outputs.version }}"
