name: Update Goldens

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update_goldens:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout selected branch
        uses: actions/checkout@v7
        with:
          ref: ${{ github.ref_name }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Update goldens
        run: flutter test packages --update-goldens

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v3
        id: generate-token
        with:
          client-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ steps.generate-token.outputs.token }}
          sign-commits: true
          title: "chore: update goldens"
          commit-message: "chore: update goldens"
          branch: "update-goldens/${{ github.ref_name }}"
          delete-branch: true
          body: |
            ### 🤖 Golden Update
            New visual snapshots have been generated to match the current output.

            *Generated by: ${{ github.workflow }}*
          labels: automated pr
